### ISSUE TITLE
uninitialized constant Rails

### ISSUE THREAD

**Issue by danil-z** [pat/combustion#27]
i've created new engine using `rails plugin new some --mountable -T`
and followed readme for basic setup
when i try to run rackup i got following error
what do i miss?

```
Mac-mini:some danil$ rackup
/Users/danil/Sites/temp/some/lib/some/engine.rb:2:in `<module:Some>': uninitialized constant Rails (NameError)
    from /Users/danil/Sites/temp/some/lib/some/engine.rb:1:in `<top (required)>'
    from /Users/danil/Sites/temp/some/lib/some.rb:1:in `require'
    from /Users/danil/Sites/temp/some/lib/some.rb:1:in `<top (required)>'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `require'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `each'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `block in require'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `each'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `require'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327@global/gems/bundler-1.2.3/lib/bundler.rb:128:in `require'
    from /Users/danil/Sites/temp/some/config.ru:5:in `block in <main>'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
    from /Users/danil/Sites/temp/some/config.ru:1:in `new'
    from /Users/danil/Sites/temp/some/config.ru:1:in `<main>'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.1/lib/rack/builder.rb:40:in `eval'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.1/lib/rack/builder.rb:40:in `parse_file'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.1/lib/rack/server.rb:200:in `app'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.1/lib/rack/server.rb:301:in `wrapped_app'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.1/lib/rack/server.rb:252:in `start'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.1/lib/rack/server.rb:137:in `start'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/gems/rack-1.4.1/bin/rackup:4:in `<top (required)>'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/bin/rackup:19:in `load'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/bin/rackup:19:in `<main>'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/danil/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by replaid** [comment]
Just spent hours resolving this. I suggest that the README's Usage section could begin with a prominent warning that problems can occur if gems are specified as development dependencies in the gemspec and not directly in the Gemfile. This is unusual and nonintuitive.

**Comment by parndt** [comment]
@replaid thanks for the feedback; given it's fresh in your mind, how would you feel about opening a pull request adding a warning like this to aid future users? :heart:

**Comment by pat** [comment]
I'm not sure we want to recommend `combustion` or `rails` to be listed in the Gemfile. As you've noted John, this isn't the usual approach to things. Ideally, if both are standard dependencies (development or runtime), then having them in the gemspec _should_ work. That's certainly how I use Combustion in my own projects.

If anyone comes across this issue and finds this is not the case - I'd love to view the source code and stack traces if possible (if the libraries are open-sourced).

**Comment by parndt** [comment]
Ah thanks @pat 	!
