### ISSUE TITLE
Error while building the package

### ISSUE THREAD

**Issue by utkarsh2102** [pat/combustion#95]
I am getting the following errors while building the package.
Please check the same.

```
Invalid gemspec in [combustion.gemspec]: combustion.gemspec:34: syntax error, unexpected keyword_end, expecting end-of-input
Invalid gemspec in [combustion.gemspec.gem2deb]: combustion.gemspec.gem2deb:34: syntax error, unexpected keyword_end, expecting end-of-input
Traceback (most recent call last):
	11: from /usr/bin/dh_ruby:96:in `<main>'
	10: from /usr/lib/ruby/vendor_ruby/gem2deb/dh_ruby.rb:43:in `clean'
	 9: from /usr/lib/ruby/vendor_ruby/gem2deb/dh_ruby.rb:201:in `installers'
	 8: from /usr/lib/ruby/vendor_ruby/gem2deb/dh_ruby.rb:201:in `map'
	 7: from /usr/lib/ruby/vendor_ruby/gem2deb/dh_ruby.rb:202:in `block in installers'
	 6: from /usr/lib/ruby/vendor_ruby/gem2deb/dh_ruby.rb:202:in `new'
	 5: from /usr/lib/ruby/vendor_ruby/gem2deb/installer.rb:24:in `initialize'
	 4: from /usr/lib/ruby/vendor_ruby/gem2deb/installer.rb:24:in `new'
	 3: from /usr/lib/ruby/vendor_ruby/gem2deb/metadata.rb:33:in `initialize'
	 2: from /usr/lib/ruby/vendor_ruby/gem2deb/metadata.rb:33:in `chdir'
	 1: from /usr/lib/ruby/vendor_ruby/gem2deb/metadata.rb:34:in `block in initialize'
/usr/lib/ruby/vendor_ruby/gem2deb/metadata.rb:124:in `load_gemspec': E: cannot load gemspec combustion.gemspec (RuntimeError)
```

**Comment by pat** [comment]
The gem builds fine for me on Ruby 2.6.0 - can you confirm which version of Ruby you're using? Also, can you share the contents of your gemspec?

**Comment by pat** [comment]
Closing this issue as it's been dormant for a month. If you're still seeing issues, please do comment here anyway.
